# Generated by Django 3.1.7 on 2021-03-28 22:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadesAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fortaleza', models.BooleanField(blank=True, verbose_name='Fortaleza')),
                ('interior', models.BooleanField(blank=True, verbose_name='Interior')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadesatuacao_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cidade de Atuacão',
                'verbose_name_plural': 'Cidades de Atuacão',
            },
        ),
        migrations.CreateModel(
            name='CidadesRealizacaoProvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadesrealizacaoprovas_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadesrealizacaoprovas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cidade da Realizacao da Prova',
                'verbose_name_plural': 'Cidades Realizacao Provas',
            },
        ),
        migrations.CreateModel(
            name='Editais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('pago', models.BooleanField(blank=True, verbose_name='Pago')),
                ('interior', models.BooleanField(blank=True, verbose_name='Interior')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='editais_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='editais_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('identidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identidade')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereco')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('curso', models.CharField(blank=True, choices=[('1', 'Direito')], default='Direito', max_length=255, null=True, verbose_name='Curso')),
                ('comarcas_de_cidades', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comarcas De Cidades')),
                ('deficiente', models.BooleanField(blank=True, verbose_name='Deficiente')),
                ('condicao_especial', models.BooleanField(blank=True, verbose_name='Condição Especial')),
                ('descricao_deficiencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Deficiencia')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo')),
                ('condicao_especial_descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condição Especial Descrição')),
                ('documento_comprobatorio_isencao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Documento Comprobatorio Isenção')),
                ('pedido_isencao', models.BooleanField(blank=True, verbose_name='Pedido Isenção')),
                ('cota_racial', models.BooleanField(blank=True, verbose_name='Cota Racial')),
                ('condicao_cota_racial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condição Cota Racial')),
                ('documento_auto_declaracao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Documento Auto Declaração')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_cidade', to='estagio.cidadesatuacao')),
                ('cidade_realizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_cidade_realizacao', to='estagio.cidadesrealizacaoprovas')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricoes_created_by', to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_edital', to='estagio.editais')),
            ],
            options={
                'verbose_name': 'Inscricão',
                'verbose_name_plural': 'Inscricoes',
            },
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='universidades_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='universidades_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Universidade',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turnos_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turnos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nota', models.IntegerField(blank=True, help_text='?', null=True, verbose_name='Nota')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_created_by', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.ForeignKey(blank=True, help_text='?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_inscricao', to='estagio.inscricoes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_turno', to='estagio.turnos'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='universidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_universidade', to='estagio.universidades'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricoes_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InscricaoCidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('turno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Turno')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricaocidades_created_by', to=settings.AUTH_USER_MODEL)),
                ('inscricao_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricaocidades_inscricao_id', to='estagio.inscricoes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricaocidades_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscricao Cidade',
                'verbose_name_plural': 'Inscricao Cidades',
            },
        ),
        migrations.CreateModel(
            name='CidadesOrgaoAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadesorgaoatuacao_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadesorgaoatuacao_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cidade do Orgão de Atuação',
                'verbose_name_plural': 'Cidades dos Orgãos de Atuação',
            },
        ),
        migrations.AddField(
            model_name='cidadesatuacao',
            name='edital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidadesatuacao_edital_id', to='estagio.editais'),
        ),
        migrations.AddField(
            model_name='cidadesatuacao',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidadesatuacao_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo Barras')),
                ('pago', models.BooleanField(blank=True, verbose_name='Pago')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('banco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco')),
                ('valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('valor_pago', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Pago')),
                ('data_credito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Credito')),
                ('forma_pagamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma Pagamento')),
                ('sequencial_guia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sequencial Guia')),
                ('importacao_boleto_id', models.IntegerField(blank=True, null=True, verbose_name='Importação Boleto')),
                ('codigo_barras_sem_digitos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo Barras Sem Digitos')),
                ('identificador_dae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador DAE')),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boletos_created_by', to=settings.AUTH_USER_MODEL)),
                ('inscricao_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_inscricao_id', to='estagio.inscricoes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boletos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
